### ISSUE TITLE
what about polyfilling Array.prototype.find?

### ISSUE THREAD

**Issue by macool** [zhongdeliu/array-polyfill#1]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

**Comment by zhongdeliu** [comment]
Hi there, "find" isn't within the EcmaScript5 spec. Which was somehow the base back then of this polyfill collection. Although not even all ES5 array methods are present (e.g. lastIndexOf)

But of course you/anybody could update this polyfill collection with other methods.

**Comment by macool** [comment]
@zhongdeliu well I'm using `array-find` myself https://github.com/noggalito/porttare-frontend/blob/master/bower.json#L20
